export default [
    {
        name: 'base',
        data: {},
        items: [
            { name: 'background', source: '/assets/background.hdr', type: 'hdr' },
            { name: 'lennaTexture', source: '/assets/lenna.png', type: 'texture' },
            { name: 'tvModel', source: '/assets/tv.glb', type: 'glb' },
            { name: 'corridorMesh', source: '/assets/corridor-mesh.glb', type: 'glb' },
            { name: 'strecherMesh', source: '/assets/strecher-mesh.glb', type: 'glb' },
            { name: 'chairMesh', source: '/assets/chair-mesh.glb', type: 'glb' },
            { name: 'player1', source: '/assets/exports/runner.glb', type: 'glb' },
            { name: 'player2', source: '/assets/exports/catcher.glb', type: 'glb' },
            { name: 'pizzaMesh', source: '/assets/pizza.glb', type: 'glb' },
            { name: "slideMesh", source: "/assets/corridor-mesh-slide.glb", type: "glb" },
            { name: "corridor1_1", source: "/assets/corridor1_1.glb", type: "glb" },
            { name: "corridor1_2", source: "/assets/corridor1_2.glb", type: "glb" },
            { name: "corridor2_1", source: "/assets/corridor2_1.glb", type: "glb" },
            { name: "corridor2_2", source: "/assets/corridor2_2.glb", type: "glb" },
            { name: "corridor3_1", source: "/assets/corridor3_1.glb", type: "glb" },
            { name: "corridor3_2", source: "/assets/corridor3_2.glb", type: "glb" },
            { name: "corridor4_1", source: "/assets/corridor4_1.glb", type: "glb" },
            { name: "corridor4_2", source: "/assets/corridor4_2.glb", type: "glb" },
        ],
    },
];
